# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b2d6ffa76c2ae6b3a96391a39e6baa2ace6acd0961d262f9da4231bbbacd71ce23cb304ee6aa264578220faa6cd389e87179f9b7344be8611d537048ceda043

test:
  secret_key_base: 413f63f458841be6c747a01e7d2b5f9f964dfd4ce292397386bccff40e17b7a8f57e026ff3dc35d7c791fd562b65d87262f8fc4d5e55fe7c3bb2d042c08b76ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
